# Set update schedule for GitHub actions and other package managers

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      prefix: "ci"