name: 'iOS pipelines'
description: 'Run pipelines to validate code before merge or deploy afterwards'
inputs:
  WORKSPACE:
    description: 'Workspace used to build the project/package if there is one in the repo'
    required: false
  SCHEME:
    description: 'The scheme to build the project/package against'
    required: true
  XCODE_VERSION:
    description: 'The version of Xcode to build the iOS project/package from'
    required: true
    default: 15.4
  RUN_DESTINATION:
    description: 'A destination specifier describing the device (or devices) to use as a destination'
    required: true
    default: platform=iOS Simulator,name=iPhone 15,OS=17.5
  SONAR_TOKEN:
    description: 'A token for SonarCloud to enable the workflow to read and upload new quality reports.'
    required: true
  GITHUB_TOKEN:
    description: 'A GitHub API token that is automatically created by the workflow. This is required for release workflows to upload new release artefacts.'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      with:
        lfs: 'true'
        fetch-depth: 0

    - name: Run Linter
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        brew install swiftlint
        swiftlint --strict
      shell: bash

    - name: Validate Pull Request Name
      if: ${{ github.event_name == 'pull_request' }}
      uses: Oliver-Binns/Versioning@4695fba9f63bed5b557094f9a64f7a2b1a7639e8 # pin@v1.1.0
      with:
        ACTION_TYPE: 'Validate'

    - name: Xcode Select
      run: |
        sudo xcode-select -s /Applications/Xcode_${{ inputs.XCODE_VERSION }}.app
      shell: bash

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild -workspace "${{ inputs.WORKSPACE }}" -scheme ${{ inputs.SCHEME }} test \
          -destination "${{ inputs.RUN_DESTINATION }}" \
          -enableCodeCoverage YES \
          -resultBundlePath result.xcresult | xcbeautify
      shell: bash

    - name: Set up Sonar
      run: |
        ${{ github.action_path }}/scripts/sonar-properties.sh ${{ github.repository_owner }} ${{ github.event.repository.name }} > sonar-project.properties
        ${{ github.action_path }}/scripts/xccov-to-sonarqube-generic.sh result.xcresult > sonarqube-generic-coverage.xml
        brew install sonar-scanner
      shell: bash

    - name: Run Pull Request SonarCloud Scanning
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

        sonar-scanner \
          -Dsonar.token=${{ inputs.SONAR_TOKEN }} \
          -Dsonar.coverageReportPaths="sonarqube-generic-coverage.xml" \
          -Dsonar.pullrequest.key=$pull_number \
          -Dsonar.pullrequest.branch=${{ github.head_ref }} \
          -Dsonar.pullrequest.base=${{ github.base_ref }}
      shell: bash

    - name: Check SonarCloud Results
      if: ${{ github.event_name == 'pull_request' }}
      uses: sonarsource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496 # pin@v1.1.0
      env:
        SONAR_TOKEN: ${{ inputs.SONAR_TOKEN }}

    - name: Run Merge SonarCloud Scanning
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        sonar-scanner \
          -Dsonar.token=${{ inputs.SONAR_TOKEN }} \
          -Dsonar.coverageReportPaths="sonarqube-generic-coverage.xml"
      shell: bash

    - name: Increment Version
      if: ${{ github.event_name != 'pull_request' }}
      id: versioning
      uses: Oliver-Binns/Versioning@4695fba9f63bed5b557094f9a64f7a2b1a7639e8 # pin@v1.1.0
      with:
        ACTION_TYPE: 'Release'
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
